name: valxapp
description: "Valorant Checker Mobile - Versión Móvil Mejorada"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP y Networking
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^5.0.2
  
  # WebView para login manual
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2
  
  # Estado y Gestión de Datos
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # UI y Componentes
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Almacenamiento Local
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  
  # Utilidades
  intl: ^0.18.1
  crypto: ^3.0.3
  uuid: ^4.2.1
  
  # Permisos
  permission_handler: ^11.1.0
  
  # Notificaciones
  flutter_local_notifications: ^17.0.0
  
  # Logging
  logger: ^2.0.2+1
  
  # Archivos
  file_picker: ^10.2.2
  
  # UI Avanzada
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Animaciones
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/valx_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/valx_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/valx_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/valx_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
